name: muslim_life_mosque_edition
description: "Masjid Pulse"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.4
  flutter_spinkit: ^5.2.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  liquid_swipe: ^3.1.0
  uuid: ^4.5.1
  flutter_animate: ^4.5.2
  delightful_toast: ^1.1.0
  adhan: ^2.0.0+1
  flutter_countdown_timer: ^4.1.0
  gap: ^3.0.1
  shared_preferences: ^2.5.3
  internet_connection_checker_plus: ^2.7.2
  http: ^1.3.0
  lehttp_overrides: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: BoldFont
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf

    - family: MediumFont
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

    - family: RegularFont
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: LightFont
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
        
    - family: ExtraLightFont
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
    
    - family: BoldNarrowFont
      fonts:
        - asset: assets/fonts/PTSansNarrow-Bold.ttf

    - family: ArabicHeaderFont
      fonts:
        - asset: assets/fonts/NotoKufiArabic.ttf

    - family: ArabicFont
      fonts:
        - asset: assets/fonts/NotoKufiArabic.ttf

  
# flutter_native_splash-production.yaml
flutter_native_splash:
  color: "#ECF6F3"
  image: assets/images/app_logo.png
  #branding: assets/images/app_brand.png
  color_dark: "#ECF6F3"
  image_dark: assets/images/app_logo.png
  #branding_dark: assets/images/app_brand.png

  android_12:
    image: assets/images/app_logo_12.png
    icon_background_color: "#ECF6F3"
    image_dark: assets/images/app_logo_12.png
    icon_background_color_dark: "#ECF6F3"

  web: false